### PR TITLE
Bug hunt bot PoC

### LINKED ISSUE #20: Bug Hunt Bot PoC for AE
- [x] Try to iterate over the spreadsheet
- [x] Format message
- [x] Try to postpone bugs in the spreadsheet
- [x] Add comments to bugs in the spreadsheet

### PR DESCRIPTION
**Pull request by eliseealex**
Finished the first iteration for Bug Hunt Bot

Closes: #20

### CODE REVIEW

File: experimental-bot/src/main/kotlin/press/lis/greeb/bug_hunt/BugHuntBot.kt [hunk 1]
```diff
@@ -0,0 +1,195 @@
...
+                    logger.info("Trying to send:\n$message")
+
+                    sendMessage.text = message
+                    sendMessage.enableMarkdown(true)
+                }
+
+                else -> {
+                    val commentToAdd = "${nowDate.format(dateTimeFormatter)} -> $inputText"
+                    sendMessage.text = """
+                        Will add to the comment (will rewrite the last try):
```
Comment (FhtagnEast) [inline experimental-bot/src/main/kotlin/press/lis/greeb/bug_hunt/BugHuntBot.kt:119]: Does it really rewrites the last try?

**Review by FhtagnEast — APPROVED** [review]
